BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Team" (
	"id"	INTEGER,
	"name"	TEXT,
	PRIMARY KEY("id" AUTOINCREMENT)
);
INSERT INTO "Team" VALUES (1,'KRC Genk');
INSERT INTO "Team" VALUES (2,'Beerschot AC');
INSERT INTO "Team" VALUES (3,'SV Zulte-Waregem');
INSERT INTO "Team" VALUES (4,'Sporting Lokeren');
INSERT INTO "Team" VALUES (5,'KSV Cercle Brugge');
INSERT INTO "Team" VALUES (6,'RSC Anderlecht');
INSERT INTO "Team" VALUES (7,'KAA Gent');
INSERT INTO "Team" VALUES (8,'RAEC Mons');
INSERT INTO "Team" VALUES (9,'FCV Dender EH');
INSERT INTO "Team" VALUES (10,'Standard de Liège');
INSERT INTO "Team" VALUES (11,'KV Mechelen');
INSERT INTO "Team" VALUES (12,'Club Brugge KV');
INSERT INTO "Team" VALUES (13,'KSV Roeselare');
INSERT INTO "Team" VALUES (14,'KV Kortrijk');
INSERT INTO "Team" VALUES (15,'Tubize');
INSERT INTO "Team" VALUES (16,'Royal Excel Mouscron');
INSERT INTO "Team" VALUES (17,'KVC Westerlo');
INSERT INTO "Team" VALUES (18,'Sporting Charleroi');
INSERT INTO "Team" VALUES (614,'Sint-Truidense VV');
INSERT INTO "Team" VALUES (1034,'Lierse SK');
INSERT INTO "Team" VALUES (1042,'KAS Eupen');
INSERT INTO "Team" VALUES (1513,'Oud-Heverlee Leuven');
INSERT INTO "Team" VALUES (2004,'Waasland-Beveren');
INSERT INTO "Team" VALUES (2476,'KV Oostende');
INSERT INTO "Team" VALUES (2510,'Royal Excel Mouscron');
INSERT INTO "Team" VALUES (3457,'Manchester United');
INSERT INTO "Team" VALUES (3458,'Newcastle United');
INSERT INTO "Team" VALUES (3459,'Arsenal');
INSERT INTO "Team" VALUES (3460,'West Bromwich Albion');
INSERT INTO "Team" VALUES (3461,'Sunderland');
INSERT INTO "Team" VALUES (3462,'Liverpool');
INSERT INTO "Team" VALUES (3463,'West Ham United');
INSERT INTO "Team" VALUES (3464,'Wigan Athletic');
INSERT INTO "Team" VALUES (3465,'Aston Villa');
INSERT INTO "Team" VALUES (3466,'Manchester City');
INSERT INTO "Team" VALUES (3467,'Everton');
INSERT INTO "Team" VALUES (3468,'Blackburn Rovers');
INSERT INTO "Team" VALUES (3469,'Middlesbrough');
INSERT INTO "Team" VALUES (3470,'Tottenham Hotspur');
INSERT INTO "Team" VALUES (3471,'Bolton Wanderers');
INSERT INTO "Team" VALUES (3472,'Stoke City');
INSERT INTO "Team" VALUES (3473,'Hull City');
INSERT INTO "Team" VALUES (3474,'Fulham');
INSERT INTO "Team" VALUES (3475,'Chelsea');
INSERT INTO "Team" VALUES (3476,'Portsmouth');
INSERT INTO "Team" VALUES (4218,'Birmingham City');
INSERT INTO "Team" VALUES (4225,'Wolverhampton Wanderers');
INSERT INTO "Team" VALUES (4234,'Burnley');
INSERT INTO "Team" VALUES (4996,'Blackpool');
INSERT INTO "Team" VALUES (5744,'Swansea City');
INSERT INTO "Team" VALUES (5747,'Queens Park Rangers');
INSERT INTO "Team" VALUES (5756,'Norwich City');
INSERT INTO "Team" VALUES (6504,'Southampton');
INSERT INTO "Team" VALUES (6509,'Reading');
INSERT INTO "Team" VALUES (7261,'Crystal Palace');
INSERT INTO "Team" VALUES (7276,'Cardiff City');
INSERT INTO "Team" VALUES (8021,'Leicester City');
INSERT INTO "Team" VALUES (8779,'Bournemouth');
INSERT INTO "Team" VALUES (8784,'Watford');
INSERT INTO "Team" VALUES (9537,'AJ Auxerre');
INSERT INTO "Team" VALUES (9538,'FC Nantes');
INSERT INTO "Team" VALUES (9539,'Girondins de Bordeaux');
INSERT INTO "Team" VALUES (9540,'SM Caen');
INSERT INTO "Team" VALUES (9541,'Le Havre AC');
INSERT INTO "Team" VALUES (9542,'OGC Nice');
INSERT INTO "Team" VALUES (9543,'Le Mans FC');
INSERT INTO "Team" VALUES (9544,'FC Lorient');
INSERT INTO "Team" VALUES (9545,'Olympique Lyonnais');
INSERT INTO "Team" VALUES (9546,'Toulouse FC');
INSERT INTO "Team" VALUES (9547,'AS Monaco');
INSERT INTO "Team" VALUES (9548,'Paris Saint-Germain');
INSERT INTO "Team" VALUES (9549,'AS Nancy-Lorraine');
INSERT INTO "Team" VALUES (9550,'LOSC Lille');
INSERT INTO "Team" VALUES (9551,'Stade Rennais FC');
INSERT INTO "Team" VALUES (9552,'Olympique de Marseille');
INSERT INTO "Team" VALUES (9553,'FC Sochaux-Montbéliard');
INSERT INTO "Team" VALUES (9554,'Grenoble Foot 38');
INSERT INTO "Team" VALUES (9555,'Valenciennes FC');
INSERT INTO "Team" VALUES (9556,'AS Saint-Étienne');
INSERT INTO "Team" VALUES (10300,'RC Lens');
INSERT INTO "Team" VALUES (10309,'Montpellier Hérault SC');
INSERT INTO "Team" VALUES (10312,'US Boulogne Cote D''Opale');
INSERT INTO "Team" VALUES (11074,'AC Arles-Avignon');
INSERT INTO "Team" VALUES (11076,'Stade Brestois 29');
INSERT INTO "Team" VALUES (11817,'AC Ajaccio');
INSERT INTO "Team" VALUES (11822,'Évian Thonon Gaillard FC');
INSERT INTO "Team" VALUES (11825,'Dijon FCO');
INSERT INTO "Team" VALUES (12587,'Stade de Reims');
INSERT INTO "Team" VALUES (12594,'SC Bastia');
INSERT INTO "Team" VALUES (12595,'ES Troyes AC');
INSERT INTO "Team" VALUES (13343,'En Avant de Guingamp');
INSERT INTO "Team" VALUES (14106,'FC Metz');
INSERT INTO "Team" VALUES (14868,'Angers SCO');
INSERT INTO "Team" VALUES (14876,'GFC Ajaccio');
INSERT INTO "Team" VALUES (15617,'FC Bayern Munich');
INSERT INTO "Team" VALUES (15618,'Hamburger SV');
INSERT INTO "Team" VALUES (15619,'Bayer 04 Leverkusen');
INSERT INTO "Team" VALUES (15620,'Borussia Dortmund');
INSERT INTO "Team" VALUES (15621,'FC Schalke 04');
INSERT INTO "Team" VALUES (15622,'Hannover 96');
INSERT INTO "Team" VALUES (15623,'VfL Wolfsburg');
INSERT INTO "Team" VALUES (15624,'1. FC Köln');
INSERT INTO "Team" VALUES (15625,'Eintracht Frankfurt');
INSERT INTO "Team" VALUES (15626,'Hertha BSC Berlin');
INSERT INTO "Team" VALUES (15627,'DSC Arminia Bielefeld');
INSERT INTO "Team" VALUES (15628,'SV Werder Bremen');
INSERT INTO "Team" VALUES (15629,'FC Energie Cottbus');
INSERT INTO "Team" VALUES (15630,'TSG 1899 Hoffenheim');
INSERT INTO "Team" VALUES (15631,'Borussia Mönchengladbach');
INSERT INTO "Team" VALUES (15632,'VfB Stuttgart');
INSERT INTO "Team" VALUES (15633,'Karlsruher SC');
INSERT INTO "Team" VALUES (15634,'VfL Bochum');
INSERT INTO "Team" VALUES (16237,'SC Freiburg');
INSERT INTO "Team" VALUES (16239,'1. FC Nürnberg');
INSERT INTO "Team" VALUES (16243,'1. FSV Mainz 05');
INSERT INTO "Team" VALUES (16848,'1. FC Kaiserslautern');
INSERT INTO "Team" VALUES (16850,'FC St. Pauli');
INSERT INTO "Team" VALUES (17465,'FC Augsburg');
INSERT INTO "Team" VALUES (18074,'Fortuna Düsseldorf');
INSERT INTO "Team" VALUES (18079,'SpVgg Greuther Fürth');
INSERT INTO "Team" VALUES (18691,'Eintracht Braunschweig');
INSERT INTO "Team" VALUES (19305,'SC Paderborn 07');
INSERT INTO "Team" VALUES (19916,'FC Ingolstadt 04');
INSERT INTO "Team" VALUES (19917,'SV Darmstadt 98');
INSERT INTO "Team" VALUES (20513,'Atalanta');
INSERT INTO "Team" VALUES (20514,'Siena');
INSERT INTO "Team" VALUES (20515,'Cagliari');
INSERT INTO "Team" VALUES (20516,'Lazio');
INSERT INTO "Team" VALUES (20517,'Catania');
INSERT INTO "Team" VALUES (20518,'Genoa');
INSERT INTO "Team" VALUES (20519,'Chievo Verona');
INSERT INTO "Team" VALUES (20520,'Reggio Calabria');
INSERT INTO "Team" VALUES (20521,'Fiorentina');
INSERT INTO "Team" VALUES (20522,'Juventus');
INSERT INTO "Team" VALUES (20523,'Milan');
INSERT INTO "Team" VALUES (20524,'Bologna');
INSERT INTO "Team" VALUES (20525,'Roma');
INSERT INTO "Team" VALUES (20526,'Napoli');
INSERT INTO "Team" VALUES (20527,'Sampdoria');
INSERT INTO "Team" VALUES (20528,'Inter');
INSERT INTO "Team" VALUES (20529,'Torino');
INSERT INTO "Team" VALUES (20530,'Lecce');
INSERT INTO "Team" VALUES (20531,'Udinese');
INSERT INTO "Team" VALUES (20532,'Palermo');
INSERT INTO "Team" VALUES (21280,'Bari');
INSERT INTO "Team" VALUES (21285,'Livorno');
INSERT INTO "Team" VALUES (21292,'Parma');
INSERT INTO "Team" VALUES (22042,'Cesena');
INSERT INTO "Team" VALUES (22044,'Brescia');
INSERT INTO "Team" VALUES (22805,'Novara');
INSERT INTO "Team" VALUES (23523,'Pescara');
INSERT INTO "Team" VALUES (24273,'Hellas Verona');
INSERT INTO "Team" VALUES (24288,'Sassuolo');
INSERT INTO "Team" VALUES (25048,'Empoli');
INSERT INTO "Team" VALUES (25791,'Frosinone');
INSERT INTO "Team" VALUES (25804,'Carpi');
INSERT INTO "Team" VALUES (26547,'Vitesse');
INSERT INTO "Team" VALUES (26548,'FC Groningen');
INSERT INTO "Team" VALUES (26549,'Roda JC Kerkrade');
INSERT INTO "Team" VALUES (26550,'FC Twente');
INSERT INTO "Team" VALUES (26551,'Willem II');
INSERT INTO "Team" VALUES (26552,'Ajax');
INSERT INTO "Team" VALUES (26553,'N.E.C.');
INSERT INTO "Team" VALUES (26554,'De Graafschap');
INSERT INTO "Team" VALUES (26555,'FC Utrecht');
INSERT INTO "Team" VALUES (26556,'PSV');
INSERT INTO "Team" VALUES (26557,'Heracles Almelo');
INSERT INTO "Team" VALUES (26558,'Feyenoord');
INSERT INTO "Team" VALUES (26559,'Sparta Rotterdam');
INSERT INTO "Team" VALUES (26560,'ADO Den Haag');
INSERT INTO "Team" VALUES (26561,'FC Volendam');
INSERT INTO "Team" VALUES (26562,'SC Heerenveen');
INSERT INTO "Team" VALUES (26563,'AZ');
INSERT INTO "Team" VALUES (26564,'NAC Breda');
INSERT INTO "Team" VALUES (27161,'RKC Waalwijk');
INSERT INTO "Team" VALUES (27168,'VVV-Venlo');
INSERT INTO "Team" VALUES (27780,'Excelsior');
INSERT INTO "Team" VALUES (29000,'PEC Zwolle');
INSERT INTO "Team" VALUES (29617,'SC Cambuur');
INSERT INTO "Team" VALUES (29624,'Go Ahead Eagles');
INSERT INTO "Team" VALUES (30222,'FC Dordrecht');
INSERT INTO "Team" VALUES (31443,'Wisła Kraków');
INSERT INTO "Team" VALUES (31444,'Polonia Bytom');
INSERT INTO "Team" VALUES (31445,'Polonia Bytom');
INSERT INTO "Team" VALUES (31446,'Ruch Chorzów');
INSERT INTO "Team" VALUES (31447,'Legia Warszawa');
INSERT INTO "Team" VALUES (31448,'P. Warszawa');
INSERT INTO "Team" VALUES (31449,'Śląsk Wrocław');
INSERT INTO "Team" VALUES (31450,'Lechia Gdańsk');
INSERT INTO "Team" VALUES (31451,'Widzew Łódź');
INSERT INTO "Team" VALUES (31452,'Odra Wodzisław');
INSERT INTO "Team" VALUES (31453,'Lech Poznań');
INSERT INTO "Team" VALUES (31454,'GKS Bełchatów');
INSERT INTO "Team" VALUES (31455,'Arka Gdynia');
INSERT INTO "Team" VALUES (31456,'Jagiellonia Białystok');
INSERT INTO "Team" VALUES (31457,'Piast Gliwice');
INSERT INTO "Team" VALUES (31458,'Cracovia');
INSERT INTO "Team" VALUES (31925,'Korona Kielce');
INSERT INTO "Team" VALUES (31928,'Zagłębie Lubin');
INSERT INTO "Team" VALUES (32409,'Widzew Łódź');
INSERT INTO "Team" VALUES (32891,'Podbeskidzie Bielsko-Biała');
INSERT INTO "Team" VALUES (33377,'Pogoń Szczecin');
INSERT INTO "Team" VALUES (33855,'Zawisza Bydgoszcz');
INSERT INTO "Team" VALUES (34337,'Górnik Łęczna');
INSERT INTO "Team" VALUES (34816,'Termalica Bruk-Bet Nieciecza');
INSERT INTO "Team" VALUES (35283,'FC Porto');
INSERT INTO "Team" VALUES (35284,'CF Os Belenenses');
INSERT INTO "Team" VALUES (35285,'Sporting CP');
INSERT INTO "Team" VALUES (35286,'Trofense');
INSERT INTO "Team" VALUES (35287,'Vitória Guimarães');
INSERT INTO "Team" VALUES (35288,'Vitória Setúbal');
INSERT INTO "Team" VALUES (35289,'FC Paços de Ferreira');
INSERT INTO "Team" VALUES (35290,'SC Braga');
INSERT INTO "Team" VALUES (35291,'Amadora');
INSERT INTO "Team" VALUES (35292,'Académica de Coimbra');
INSERT INTO "Team" VALUES (35293,'Rio Ave FC');
INSERT INTO "Team" VALUES (35294,'SL Benfica');
INSERT INTO "Team" VALUES (35295,'Leixões SC');
INSERT INTO "Team" VALUES (35296,'CD Nacional');
INSERT INTO "Team" VALUES (35297,'Naval 1° de Maio');
INSERT INTO "Team" VALUES (35298,'CS Marítimo');
INSERT INTO "Team" VALUES (35769,'União de Leiria, SAD');
INSERT INTO "Team" VALUES (35774,'S.C. Olhanense');
INSERT INTO "Team" VALUES (36248,'Portimonense');
INSERT INTO "Team" VALUES (36253,'SC Beira Mar');
INSERT INTO "Team" VALUES (36723,'Feirense');
INSERT INTO "Team" VALUES (36735,'Gil Vicente FC');
INSERT INTO "Team" VALUES (37210,'Moreirense FC');
INSERT INTO "Team" VALUES (37214,'Estoril Praia');
INSERT INTO "Team" VALUES (37696,'FC Arouca');
INSERT INTO "Team" VALUES (38173,'FC Penafiel');
INSERT INTO "Team" VALUES (38176,'Boavista FC');
INSERT INTO "Team" VALUES (38789,'Uniao da Madeira');
INSERT INTO "Team" VALUES (38791,'Tondela');
INSERT INTO "Team" VALUES (39387,'Falkirk');
INSERT INTO "Team" VALUES (39388,'Rangers');
INSERT INTO "Team" VALUES (39389,'Heart of Midlothian');
INSERT INTO "Team" VALUES (39390,'Motherwell');
INSERT INTO "Team" VALUES (39391,'Kilmarnock');
INSERT INTO "Team" VALUES (39392,'Hibernian');
INSERT INTO "Team" VALUES (39393,'Aberdeen');
INSERT INTO "Team" VALUES (39394,'Inverness Caledonian Thistle');
INSERT INTO "Team" VALUES (39395,'Celtic');
INSERT INTO "Team" VALUES (39396,'St. Mirren');
INSERT INTO "Team" VALUES (39397,'Hamilton Academical FC');
INSERT INTO "Team" VALUES (39398,'Dundee United');
INSERT INTO "Team" VALUES (39853,'St. Johnstone FC');
INSERT INTO "Team" VALUES (40757,'Dunfermline Athletic');
INSERT INTO "Team" VALUES (41216,'Dundee FC');
INSERT INTO "Team" VALUES (41217,'Ross County FC');
INSERT INTO "Team" VALUES (41673,'Partick Thistle F.C.');
INSERT INTO "Team" VALUES (43035,'Valencia CF');
INSERT INTO "Team" VALUES (43036,'RCD Mallorca');
INSERT INTO "Team" VALUES (43037,'CA Osasuna');
INSERT INTO "Team" VALUES (43038,'Villarreal CF');
INSERT INTO "Team" VALUES (43039,'RC Deportivo de La Coruña');
INSERT INTO "Team" VALUES (43040,'Real Madrid CF');
INSERT INTO "Team" VALUES (43041,'CD Numancia');
INSERT INTO "Team" VALUES (43042,'FC Barcelona');
INSERT INTO "Team" VALUES (43043,'Racing Santander');
INSERT INTO "Team" VALUES (43044,'Sevilla FC');
INSERT INTO "Team" VALUES (43045,'Real Sporting de Gijón');
INSERT INTO "Team" VALUES (43046,'Getafe CF');
INSERT INTO "Team" VALUES (43047,'Real Betis Balompié');
INSERT INTO "Team" VALUES (43048,'RC Recreativo');
INSERT INTO "Team" VALUES (43049,'RCD Espanyol');
INSERT INTO "Team" VALUES (43050,'Real Valladolid');
INSERT INTO "Team" VALUES (43051,'Athletic Club de Bilbao');
INSERT INTO "Team" VALUES (43052,'UD Almería');
INSERT INTO "Team" VALUES (43053,'Atlético Madrid');
INSERT INTO "Team" VALUES (43054,'Málaga CF');
INSERT INTO "Team" VALUES (43800,'Xerez Club Deportivo');
INSERT INTO "Team" VALUES (43803,'Real Zaragoza');
INSERT INTO "Team" VALUES (43804,'CD Tenerife');
INSERT INTO "Team" VALUES (44557,'Hércules Club de Fútbol');
INSERT INTO "Team" VALUES (44565,'Levante UD');
INSERT INTO "Team" VALUES (44569,'Real Sociedad');
INSERT INTO "Team" VALUES (45330,'Granada CF');
INSERT INTO "Team" VALUES (45333,'Rayo Vallecano');
INSERT INTO "Team" VALUES (46087,'RC Celta de Vigo');
INSERT INTO "Team" VALUES (46848,'Elche CF');
INSERT INTO "Team" VALUES (47605,'SD Eibar');
INSERT INTO "Team" VALUES (47612,'Córdoba CF');
INSERT INTO "Team" VALUES (48358,'UD Las Palmas');
INSERT INTO "Team" VALUES (49115,'Grasshopper Club Zürich');
INSERT INTO "Team" VALUES (49116,'AC Bellinzona');
INSERT INTO "Team" VALUES (49117,'BSC Young Boys');
INSERT INTO "Team" VALUES (49118,'FC Basel');
INSERT INTO "Team" VALUES (49119,'FC Aarau');
INSERT INTO "Team" VALUES (49120,'FC Sion');
INSERT INTO "Team" VALUES (49121,'FC Luzern');
INSERT INTO "Team" VALUES (49122,'FC Vaduz');
INSERT INTO "Team" VALUES (49123,'Neuchâtel Xamax');
INSERT INTO "Team" VALUES (49124,'FC Zürich');
INSERT INTO "Team" VALUES (49479,'FC St. Gallen');
INSERT INTO "Team" VALUES (49837,'FC Thun');
INSERT INTO "Team" VALUES (50201,'Servette FC');
INSERT INTO "Team" VALUES (50204,'FC Lausanne-Sports');
INSERT INTO "Team" VALUES (51606,'Lugano');
COMMIT;
