insert into stadium(name, city, country) values ('Santiago Bernabéu', 'Madrid', 'Spain');
insert into stadium(name, city, country) values ('Camp Nou', 'Barcelona', 'Spain');
insert into stadium(name, city, country) values ('Old Trafford', 'Manchester', 'England');
insert into stadium(name, city, country) values ('Stamford Bridge', 'London', 'England');
insert into stadium(name, city, country) values ('Parc des Princes', 'Paris', 'France');
insert into stadium(name, city, country) values ('Stade Vélodrome', 'Marseille', 'France');
insert into stadium(name, city, country) values ('Allianz Arena', 'Munich', 'Germany');
insert into stadium(name, city, country) values ('Signal Iduna Park', 'Dortmund', 'Germany');
insert into stadium(name, city, country) values ('Juventus Stadium', 'Turin', 'Italy');
insert into stadium(name, city, country) values ('Giuseppe Meazza', 'Milan', 'Italy');

insert into club(name, stadium_id) values ('Real Madrid', 1);
insert into club(name, stadium_id) values ('FC Barcelona', 2);
insert into club(name, stadium_id) values ('Manchester United', 3);
insert into club(name, stadium_id) values ('Chelsea', 4);
insert into club(name, stadium_id) values ('Paris Saint-Germain', 5);
insert into club(name, stadium_id) values ('Olympique de Marseille', 6);
insert into club(name, stadium_id) values ('Bayern Munich', 7);
insert into club(name, stadium_id) values ('Borussia Dortmund', 8);
insert into club(name, stadium_id) values ('Juventus', 9);
insert into club(name, stadium_id) values ('Inter Milan', 10);
